import turtle

scale = 10

def curve(f, r):
    for i in range(4):
        turtle.forward(f)
        turtle.right(r)
    turtle.right(scale+5)

def earI(f):
    turtle.forward(f)
    turtle.left(scale*12)
    turtle.forward(f-5)
    turtle.left(scale*10)
    turtle.forward(f-1.5)
    turtle.left(scale*12)

turtle.speed(20)

turtle.left(scale*19+5)
curve(scale*3, scale)
for i in range (2):
    turtle.forward(scale*3)
    turtle.right(scale*9)
    turtle.forward(scale*3)
    turtle.left(scale*9)
turtle.right(scale*5)
turtle.forward(scale*8)
turtle.right(scale*13)
turtle.forward(scale*3)
turtle.left(scale*5)
curve(scale*2, scale*0.7)
turtle.left(scale*8)
turtle.forward(scale*3)
turtle.right(scale*13.6)
turtle.forward(scale*8+2)
turtle.left(scale*4.5)
for i in range (2):
    turtle.forward(scale*3)
    turtle.right(scale*9)
    turtle.forward(scale*3)
    turtle.left(scale*9)
turtle.up()
turtle.goto(scale*(-12.5), scale*8.5)
turtle.down()
turtle.left(scale*2)
curve(scale*2.05, scale*0.5)
turtle.up()
turtle.goto(-scale*0.1, scale*8.5)
turtle.down()
turtle.right(scale*9)
curve(scale*1.75, -scale*0.5)
turtle.up()
turtle.goto(scale*(-5),scale*4.8)
turtle.right(scale*3.5)
turtle.down()
turtle.forward(scale*1.3)
turtle.up()
turtle.goto(-scale*12.3, scale*16)
turtle.left(scale*9)
turtle.down()
earI(scale*1.5)
turtle.up()
turtle.goto(-scale*0.4, scale*16)
turtle.right(scale*2.1)
turtle.down()
earI(scale*1.5)
turtle.up()
turtle.goto(-scale*2, scale*5)
turtle.dot()
turtle.goto(-scale*10, scale*5)
turtle.dot()
turtle.goto(-55, 42)
turtle.left(61)
turtle.down()
turtle.forward(scale*2)
turtle.up()
turtle.goto(-40, 25)
turtle.right(80)
turtle.down()
curve(10, 10)
turtle.up()
turtle.goto(100, -100)

turtle.exitonclick()